# Generated by Django 3.2.9 on 2021-12-31 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortbio', models.TextField(default='', verbose_name='shortbio')),
                ('interests', models.CharField(max_length=100, null=True, verbose_name='interests')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('timecredit', models.PositiveIntegerField(default=5)),
                ('timecredit_hold', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=100, null=True, verbose_name='location')),
                ('occupation', models.CharField(max_length=100, null=True, verbose_name='occupation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
