# Generated by Django 3.2.9 on 2021-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shortbio',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
