# Generated by Django 3.2.9 on 2021-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(null=True, verbose_name='interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shortbio',
            field=models.TextField(null=True, verbose_name='shortbio'),
        ),
    ]
