# Generated by Django 3.2.9 on 2021-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211124_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timecredit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
