# Generated by Django 3.2.9 on 2021-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='20/12/2021'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='20/12/2021'),
        ),
    ]
