# Generated by Django 3.2.9 on 2021-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211123_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='defaultpost.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultpost.jpg', upload_to='post_pics'),
        ),
    ]
