# Generated by Django 3.2.9 on 2022-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
    ]
