# Generated by Django 3.2.9 on 2022-01-05 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20220105_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='service.offer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.offer'),
        ),
    ]
